name: net_worth_audiovisualization
description: Net Worth Audiovisiualizer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/s1.mp3
    - assets/s2.mp3
    - assets/s3.mp3
    - assets/s4.mp3
    - assets/s5.mp3
    - assets/s6.mp3
    - assets/dollar.png
